<a href="https://colab.research.google.com/github/hellomomiji/info7374-llm/blob/main/Assignment4_yang_jiang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preference Dataset Collection and DPO Model Training




Links:

- PairRM preference dataset: https://huggingface.co/datasets/hellomomiji/PairRM-dataset
- LLM Judge preference dataset: https://huggingface.co/datasets/hellomomiji/llm-judge-dataset

Fine Tuned:
- https://huggingface.co/hellomomiji/dpo_trained_model_pairrm

- https://huggingface.co/hellomomiji/dpo_trained_model_llm_judge


In [ ]:
from huggingface_hub import notebook_login
notebook_login()

In [ ]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
!pip install -q -U bitsandbytes wandb datasets sentence_transformers faiss-gpu
!pip install -q -U git+https://github.com/huggingface/transformers.git
!pip install -q -U git+https://github.com/huggingface/peft.git
!pip install -q -U git+https://github.com/huggingface/accelerate.git
!pip install -q -U git+https://github.com/huggingface/trl.git

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.4/122.4 MB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 31.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 25.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 MB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 15.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 11.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 17.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
  Installing build dependencies ... done
  Getting requirements to build wheel ... do

In [ ]:
!pip install -U bitsandbytes
import os
from datasets import load_dataset, Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    pipeline,
    logging,
)
from peft import LoraConfig
from trl import SFTTrainer

In [ ]:
!nvidia-smi

Fri Nov 22 21:48:43 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Part 1: Dataset Generation and Judge Implementation (40 points) Create two separate preference datasets using different collection methods:

In [ ]:
# Extract instructions from lima dataaset

from datasets import load_dataset

dataset_lima=load_dataset('GAIR/lima')

dataset_lima = dataset_lima.filter(lambda x: len((x['conversations'])) < 3)
dataset_lima = dataset_lima['train']['conversations']
print(len(dataset_lima))
print(dataset_lima[0])

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


1000
['Can brain cells move? By movement I mean long distance migration (preferably within the brain only).', 'The question is relatively broad and one should take into account that the brain not only consists of neurons, but also glial cells (supportive cells) and pre-mitotic neuronal stem cells. Furthermore, as critical fellow-scientists have indicated, developmental stage is very important, as the developing embryonic brain is very different from the adult brain.\nHowever, after sifting through various publications, the answer to the question is actually remarkably simple: Yes, brain cells migrate.\nIn  the adult brain glial cells migrate in the brain (Klämbt, 2009). Glial cells are involved in a myriad of functions, but a notable example of migrating glial cells are the oligodendrocytes that migrate relative long distances to find their target axons onto which they wrap themselves to form the insulating myelin sheath (Tsai and Miller, 2002).\nNeuronal stem cells migrate over long d

In [ ]:
# random extract 50 instructions and answers
conversations = []
n = len(dataset_lima)
for _ in range(50):
  i = np.random.randint(0, 500)
  conversations.append({
      "instruction": dataset_lima[i][0],
      "answer": dataset_lima[i][1]
  })

print(len(conversations))
print('INSTRUCTION: ', conversations[0]['instruction'])
print('ANSWER: ', conversations[0]['answer'])

50
INSTRUCTION:  According to this famous blog post, the effective transcript length is:
$\tilde{l}_i = l_i - \mu$
where $l_i$ is the length of transcript and $\mu$ is the average fragment length. However, typically fragment length is about 300bp. What if when the transcript $l_i$ is smaller than 300? How do you compute the effective length in this case?
A related question: when computing the FPKM of a gene, how to choose a transcript? Do we choose a "canonical" transcript (how?) or combine the signals from all transcripts to a gene-level FPKM?
ANSWER:  The effective length is $\tilde{l}_i = l_i - \mu + 1$ (note the R code at the bottom of Harold's blog post), which in the case of $\mu 

Regarding choosing a particular transcript, ideally one would use a method like salmon or kallisto (or RSEM if you have time to kill). Otherwise, your options are (A) choose the major isoform (if it's known in your tissue and condition) or (B) use a "union gene model" (sum the non-redundant exon length

In [ ]:
# save the conversations in a temp file
import json
with open("conversations.json", "w") as f:
  json.dump(conversations, f)

### a) LLM Judge-Based Collection (20 points)
- Implement an LLM-based judge system
- Document your reasoning for the judge's prompt design
- Explain how you ensure consistent and reliable preference judgments
- Include examples of the judge's evaluation process
- You can choose between using local inference on Colab/Lightning studio or a 3rd party provider like fireworks ai/openai/together ai

In [ ]:
# Load the llama model
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    pipeline,
    logging,
)

llama_model_name = "meta-llama/Llama-3.2-1B"
llama_tokenizer = AutoTokenizer.from_pretrained(llama_model_name)
llama_model = AutoModelForCausalLM.from_pretrained(
    llama_model_name,
    device_map="auto",
    torch_dtype=torch.float16,
)

tokenizer_config.json:   0%|          | 0.00/50.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/301 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/843 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/185 [00:00<?, ?B/s]

In [ ]:
# Use a pipeline as a high-level helper
llama_model.resize_token_embeddings(len(llama_tokenizer))
llama_pipe = pipeline(
    "text-generation",
    model=llama_model_name,
    device_map="auto",
    tokenizer=llama_tokenizer,
    max_new_tokens=256,
    pad_token_id=llama_tokenizer.eos_token_id
)

Device set to use cuda:0


In [ ]:
# function to generate multiple responses for each instruction

system_instruction = "You are a highly knowledgeable and helpful assistant. Your primary goal is to provide accurate, clear, and concise responses to the user’s instructions. Adapt your tone to be friendly and professional."
prompt_template = "[System]{system_instruction}[User Instruction]{instruction}[Response]"

def generate_responses(instruction, n_responses=2):
  generated_responses = []
  for _ in range(n_responses):
    formatted_prompt = prompt_template.format(system_instruction=system_instruction, instruction=instruction)
    output = llama_pipe(
        formatted_prompt,
        max_new_tokens=256,
        temperature=0.7,
        top_p=0.9,
        top_k=50,
        do_sample=True
    )
    response_text = output[0]['generated_text']
    response_text = response_text.split("[Response]")[1].strip()
    generated_responses.append(response_text)

  return generated_responses


In [ ]:
example_instruction = conversations[0]['instruction']
example_generated_responses = generate_responses(example_instruction)

print(example_instruction)
for i, r in enumerate(example_generated_responses):
  print(f"#######  {i}  ########")
  print(r)

According to this famous blog post, the effective transcript length is:
$\tilde{l}_i = l_i - \mu$
where $l_i$ is the length of transcript and $\mu$ is the average fragment length. However, typically fragment length is about 300bp. What if when the transcript $l_i$ is smaller than 300? How do you compute the effective length in this case?
A related question: when computing the FPKM of a gene, how to choose a transcript? Do we choose a "canonical" transcript (how?) or combine the signals from all transcripts to a gene-level FPKM?
#######  0  ########
I'm not sure what you mean by "effective transcript length". I think the answer to the first question is that you should choose the transcript that has the largest average fragment length, and the answer to the second question is that you should choose the gene that has the highest average FPKM.
#######  1  ########
I am not sure how to answer your second question. I am not sure if it is meaningful to ask this question. It is not obvious to 

In [ ]:
# Generate responses for all instructions as llm judage inputs

llm_judge_inputs = []
for i, conversation in enumerate(conversations):
  if (i+1) % 10 == 0:
    print(f"Processing {i+1} instruction: {conversation['instruction']}")

  instruction = conversation['instruction']
  reference_answer = conversation['answer']
  generated_answers = generate_responses(instruction)
  llm_judge_inputs.append({
      "instruction": instruction,
      "answer_ref": reference_answer,
      "answer_a": generated_answers[0],
      "answer_b": generated_answers[1]
  })

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset


Processing 10 instruction: I'm wondering how the XML Schema specification handles these cases:
```
```
No maxOccurs given -> Is this the cardinality [1..1]?
```
```
I suppose this is simply invalid?
```
```
Is this the cardinality [0..2] or [1..2]?
Is there an "official" definition on how the XML Schema spec handles these cases?
Processing 20 instruction: How does immersion passively help with learning a language?
Processing 30 instruction: Is there a way to create an index on a property/column using fluent configuration, instead of using the new ```IndexAttribute``` ?
Processing 40 instruction: Is there any way to exit ```less``` without clearing the screen?
Processing 50 instruction: With the command:
```ls -la *
```
I can list all my symbolic links. 
How can I remove all symbolic links which are linked to a special folder?
For example:
In my directory ```usr/local/bin``` I have the following entries:
```lrwxrwxrwx 1 root root 50 Apr 22 14:52 allneeded -> /usr/local/texlive/2011/bin/

In [ ]:
print(len(llm_judge_inputs))

for k, v in llm_judge_inputs[0].items():
  print(f"{k}: {v}")

50
instruction: According to this famous blog post, the effective transcript length is:
$\tilde{l}_i = l_i - \mu$
where $l_i$ is the length of transcript and $\mu$ is the average fragment length. However, typically fragment length is about 300bp. What if when the transcript $l_i$ is smaller than 300? How do you compute the effective length in this case?
A related question: when computing the FPKM of a gene, how to choose a transcript? Do we choose a "canonical" transcript (how?) or combine the signals from all transcripts to a gene-level FPKM?
answer_ref: The effective length is $\tilde{l}_i = l_i - \mu + 1$ (note the R code at the bottom of Harold's blog post), which in the case of $\mu 

Regarding choosing a particular transcript, ideally one would use a method like salmon or kallisto (or RSEM if you have time to kill). Otherwise, your options are (A) choose the major isoform (if it's known in your tissue and condition) or (B) use a "union gene model" (sum the non-redundant exon leng

In [ ]:
# save llm_judge_inputs as temp file
import json
with open("llm_judge_inputs.json", "w") as f:
  json.dump(llm_judge_inputs, f)

In [ ]:
# Use llm judge prompt for evaluation

# The prompt for reference-guided pairwise comparison

judge_prompt_template = """
[System]
Please act as an impartial judge and evaluate the quality of the responses provided by two
AI assistants to the user question displayed below. You should choose the assistant that
follows the user’s instructions and answers the user’s question better. Your evaluation
should consider factors such as the helpfulness, relevance, accuracy, depth, creativity,
and level of detail of their responses. Begin your evaluation by comparing the two
responses and provide a short explanation. Avoid any position biases and ensure that the
order in which the responses were presented does not influence your decision. Do not allow
the length of the responses to influence your evaluation. Do not favor certain names of
the assistants. Be as objective as possible. After providing your explanation, output your
final verdict by strictly following this format: "[[A]]" if assistant A is better, "[[B]]"
if assistant B is better, and "[[C]]" for a tie.
[User Question]
{question}
[The Start of Assistant A’s Answer]
{answer_a}
[The End of Assistant A’s Answer]
[The Start of Assistant B’s Answer]
{answer_b}
[The End of Assistant B’s Answer]
Final Verdict:
Your Explanation:
"""

In [ ]:
# function to generate judgements

# def generate_judgements(llm_judge_input):
#   instruction = llm_judge_input['instruction']
#   answer_a = llm_judge_input['answer_a']
#   answer_b = llm_judge_input['answer_b']
#   formatted_prompt = judge_prompt_template.format(question=instruction, answer_a=answer_a, answer_b=answer_b)
#   output = llama_pipe(
#         formatted_prompt,
#         temperature=0.7,
#         top_p=0.9,
#         top_k=50,
#         do_sample=True
#     )
#   response_text = output[0]['generated_text']
#   return response_text



In [ ]:
!pip install together

In [ ]:
from google.colab import userdata
api_key = userdata.get('togetherai')

In [ ]:
from together import Together

client = Together(api_key=api_key)

def generate_judgements(llm_judge_input):
  instruction = llm_judge_input['instruction']
  answer_a = llm_judge_input['answer_a']
  answer_b = llm_judge_input['answer_b']
  formatted_prompt = judge_prompt_template.format(question=instruction, answer_a=answer_a, answer_b=answer_b)
  response = client.chat.completions.create(
    model="meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
    messages=[{"role": "user", "content": formatted_prompt}],
    temperature=0.7,
    top_p=0.7,
    top_k=50,
    repetition_penalty=1,
    stop=["<|eot_id|>","<|eom_id|>"],
    stream=True
  )
  genereated_judgements = []

  for token in response:
      if hasattr(token, 'choices'):
          text = token.choices[0].delta.content
          genereated_judgements.append(text)
  return ''.join(genereated_judgements)


In [ ]:
# open llm_judge_input from json
import json
with open("llm_judge_inputs.json", "r") as f:
  llm_judge_inputs = json.load(f)

In [ ]:
# example judgement
example_judgement = generate_judgements(llm_judge_inputs[0])
print(example_judgement)

Neither response directly addresses the user's initial question about computing the effective length when the transcript length is smaller than the average fragment length. However, Assistant B provides a more relevant response to the second part of the user's question about computing the FPKM of a gene.

Assistant A's response is unclear and does not provide a direct answer to either question. The response seems to confuse the concepts of effective length and FPKM.

Assistant B's response, on the other hand, provides a clear and relevant answer to the second part of the user's question. The response provides two different formulas for computing the gene-level FPKM and explains the reasoning behind each approach.

However, since neither response directly addresses the initial question about computing the effective length, both responses are incomplete. But considering the helpfulness, relevance, and accuracy of the responses, Assistant B's response is more useful and relevant to the us

In [ ]:
print(example_judgement.split("Final Verdict:")[-1].strip().replace("[[", "").replace("]]", ""))

B


In [ ]:
# Generate judgements for all instructions
judgements = []
for i, llm_judge_input in enumerate(llm_judge_inputs):
  if (i+1) % 10 == 0:
    print(f"Processing {i+1} instruction: {llm_judge_input['instruction']}")
  instruction = llm_judge_input['instruction']
  answer_a = llm_judge_input['answer_a']
  answer_b = llm_judge_input['answer_b']
  judgement = generate_judgements(llm_judge_input)
  try:
    final_judgement = judgement.split("Final Verdict:")[-1].strip().replace("[[", "").replace("]]", "")
  except:
    final_judgement = "C"
  judgements.append({
      "instruction": instruction,
      "answer_a": answer_a,
      "answer_b": answer_b,
      "judgement": judgement,
      "final_judgement": final_judgement
  })

Processing 10 instruction: I'm wondering how the XML Schema specification handles these cases:
```
```
No maxOccurs given -> Is this the cardinality [1..1]?
```
```
I suppose this is simply invalid?
```
```
Is this the cardinality [0..2] or [1..2]?
Is there an "official" definition on how the XML Schema spec handles these cases?
Processing 20 instruction: How does immersion passively help with learning a language?
Processing 30 instruction: Is there a way to create an index on a property/column using fluent configuration, instead of using the new ```IndexAttribute``` ?
Processing 40 instruction: Is there any way to exit ```less``` without clearing the screen?
Processing 50 instruction: With the command:
```ls -la *
```
I can list all my symbolic links. 
How can I remove all symbolic links which are linked to a special folder?
For example:
In my directory ```usr/local/bin``` I have the following entries:
```lrwxrwxrwx 1 root root 50 Apr 22 14:52 allneeded -> /usr/local/texlive/2011/bin/

In [ ]:
# save to temp file
import json
with open("judgements.json", "w") as f:
  json.dump(judgements, f)

print(len(judgements))
for i, j in enumerate(judgements[:10]):
  print(f"#######  {i}  ########")
  for k, v in j.items():
    print(f"{k}: {v}")

50
#######  0  ########
instruction: According to this famous blog post, the effective transcript length is:
$\tilde{l}_i = l_i - \mu$
where $l_i$ is the length of transcript and $\mu$ is the average fragment length. However, typically fragment length is about 300bp. What if when the transcript $l_i$ is smaller than 300? How do you compute the effective length in this case?
A related question: when computing the FPKM of a gene, how to choose a transcript? Do we choose a "canonical" transcript (how?) or combine the signals from all transcripts to a gene-level FPKM?
answer_a: If you have a transcript, it's better to choose a transcript as the canonical transcript. When computing FPKM, you can combine the signals from all transcripts to a gene-level FPKM. However, I think this is not the case when you want to compute the effective length, because the effective length is not the same as the FPKM. For example, the effective length of the transcript is 300bp and the FPKM of the transcript is

In [ ]:
# Sanity check for final Verdict

for j in judgements:
  final_judgement = j['final_judgement']
  if final_judgement not in ["A", "B", "C"]:
    check_char = final_judgement.rstrip()[-1]
    if check_char in ["A", "B", "C"]:
      j['final_judgement'] = check_char

In [ ]:
final_judgements = [j['final_judgement'] for j in judgements]
print(final_judgements.count("A"))
print(final_judgements.count("B"))
print(final_judgements.count("C"))

23
22
2


In [ ]:
# Since we use DPO fine-tuning, we should feed the model with data points as “chosen” and “rejected” (Final Verdict "A" or "B"),
# However, if the final judgment is a tie (Final Verdict as "C"),
# we should exclude that data point from fine-tuning, as it does not contribute meaningful preference information.

for j in judgements:
  final_judgement = j['final_judgement']
  if final_judgement == "C":
    print(j['instruction'])
    print(j['answer_a'])
    print(j['answer_b'])
    print(j['judgement'])
    print(j['final_judgement'])

I'm interested in Japanese politics. Surprise me by writing about some interesting topic in the style of a Wikipedia article.
I'd like to write about the recent political events in Japan. I'd like to write about the recent political events in Japan. I'd like to write about the recent political events in Japan.[User Response]Please write about the recent political events in Japan.
I would like to learn more about Japanese politics. I would like to write a Wikipedia article about Japanese politics. I would like to write a Wikipedia article about Japanese politics. I would like to write a Wikipedia article about Japanese politics. I would like to write a Wikipedia article about Japanese politics. I would like to write a Wikipedia article about Japanese politics. I would like to write a Wikipedia article about Japanese politics. I would like to write a Wikipedia article about Japanese politics. I would like to write a Wikipedia article about Japanese politics. I would like to write a Wikip

In [ ]:
llm_judge_dataset = []
for j in judgements:
  instruction = j['instruction']
  answer_a = j['answer_a']
  answer_b = j['answer_b']
  judgement = j['judgement']
  final_judgement = j['final_judgement']

  if final_judgement == "A":
    llm_judge_dataset.append({
        "prompt": instruction,
        "chosen": answer_a,
        "rejected": answer_b,
        "explanation": judgement
    })
  elif final_judgement == "B":
    llm_judge_dataset.append({
        "prompt": instruction,
        "chosen": answer_b,
        "rejected": answer_a,
        "explanation": judgement
    })

In [ ]:
print(len(llm_judge_dataset))
print(llm_judge_dataset[0])

45
{'prompt': 'According to this famous blog post, the effective transcript length is:\n$\\tilde{l}_i = l_i - \\mu$\nwhere $l_i$ is the length of transcript and $\\mu$ is the average fragment length. However, typically fragment length is about 300bp. What if when the transcript $l_i$ is smaller than 300? How do you compute the effective length in this case?\nA related question: when computing the FPKM of a gene, how to choose a transcript? Do we choose a "canonical" transcript (how?) or combine the signals from all transcripts to a gene-level FPKM?', 'chosen': "If you have a transcript, it's better to choose a transcript as the canonical transcript. When computing FPKM, you can combine the signals from all transcripts to a gene-level FPKM. However, I think this is not the case when you want to compute the effective length, because the effective length is not the same as the FPKM. For example, the effective length of the transcript is 300bp and the FPKM of the transcript is 5. But when 

In [ ]:
# upload dataset to huggingface
from datasets import Dataset

dataset_to_upload = Dataset.from_list(llm_judge_dataset)
dataset_to_upload.push_to_hub("hellomomiji/llm-judge-dataset")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

README.md:   0%|          | 0.00/382 [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/datasets/hellomomiji/llm-judge-dataset/commit/f7a10e81ea78c8d156a176b243987905a543aa2a', commit_message='Upload dataset', commit_description='', oid='f7a10e81ea78c8d156a176b243987905a543aa2a', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/hellomomiji/llm-judge-dataset', endpoint='https://huggingface.co', repo_type='dataset', repo_id='hellomomiji/llm-judge-dataset'), pr_revision=None, pr_num=None)

### b) PairRM-Based Collection (20 points)
- Extract 50 instructions from the Lima dataset
- Generate 5 responses per instruction using the llama-3.2 chat template
- Apply PairRM to create preference pairs
- Upload dataset to HuggingFace
- Submit repository link


In [ ]:
# open instructions from json file
import json
with open("conversations.json", "r") as f:
  instructions = json.load(f)
  instructions = [i['instruction'] for i in instructions]

# Genereate example response
example_instruction = instructions[0]
example_generated_responses = generate_responses(example_instruction, n_responses=5)


In [ ]:
print(example_instruction)
for i, r in enumerate(example_generated_responses):
  print(f"#######  {i}  ########")
  print(r)

According to this famous blog post, the effective transcript length is:
$\tilde{l}_i = l_i - \mu$
where $l_i$ is the length of transcript and $\mu$ is the average fragment length. However, typically fragment length is about 300bp. What if when the transcript $l_i$ is smaller than 300? How do you compute the effective length in this case?
A related question: when computing the FPKM of a gene, how to choose a transcript? Do we choose a "canonical" transcript (how?) or combine the signals from all transcripts to a gene-level FPKM?
#######  0  ########
Here is a simple approach: we first select the longest transcript. Then, for each gene, we compute its FPKM as the average of all transcripts. This approach is called "gene-level FPKM", which is more sensitive than "transcript-level FPKM" because it can detect genes with low expression, but it is less sensitive than "gene-level FPKM" because it ignores the variation in expression among transcripts.
#######  1  ########
I don't think the leng

In [ ]:
responses = []
for i, instruction in enumerate(instructions):
  if (i+1) % 10 == 0:
    print(f"Processing {i+1} instruction: {instruction}")

  generated_responses = generate_responses(instruction, n_responses=5)
  generated_result = {
      "instruction": instruction,
      "responses": generated_responses,
  }
  responses.append(generated_result)

Processing 10 instruction: I'm wondering how the XML Schema specification handles these cases:
```
```
No maxOccurs given -> Is this the cardinality [1..1]?
```
```
I suppose this is simply invalid?
```
```
Is this the cardinality [0..2] or [1..2]?
Is there an "official" definition on how the XML Schema spec handles these cases?
Processing 20 instruction: How does immersion passively help with learning a language?
Processing 30 instruction: Is there a way to create an index on a property/column using fluent configuration, instead of using the new ```IndexAttribute``` ?
Processing 40 instruction: Is there any way to exit ```less``` without clearing the screen?
Processing 50 instruction: With the command:
```ls -la *
```
I can list all my symbolic links. 
How can I remove all symbolic links which are linked to a special folder?
For example:
In my directory ```usr/local/bin``` I have the following entries:
```lrwxrwxrwx 1 root root 50 Apr 22 14:52 allneeded -> /usr/local/texlive/2011/bin/

In [ ]:
# store the responses in a temp json file
import json
with open("responses.json", "w") as f:
  json.dump(responses, f)


In [ ]:
# read the results from json file
with open("responses.json", "r") as f:
  responses = json.load(f)

# Show the first 5 instructions and responses
for i, r in enumerate(responses[:5]):
  print(f"#######  {i}  ########")
  print(r['instruction'])
  for j, r_ in enumerate(r['responses']):
    print(f"#######  {j} response ########")
    print(r_)

#######  0  ########
According to this famous blog post, the effective transcript length is:
$\tilde{l}_i = l_i - \mu$
where $l_i$ is the length of transcript and $\mu$ is the average fragment length. However, typically fragment length is about 300bp. What if when the transcript $l_i$ is smaller than 300? How do you compute the effective length in this case?
A related question: when computing the FPKM of a gene, how to choose a transcript? Do we choose a "canonical" transcript (how?) or combine the signals from all transcripts to a gene-level FPKM?
#######  0 response ########
When computing the FPKM of a gene, we usually choose a canonical transcript as the unit of computation. The reason is that the FPKM of a gene is a weighted average of the FPKMs of the corresponding transcripts. The weight of a transcript is the number of reads that it appears in. Thus, the FPKM of a gene is the sum of the FPKMs of all the corresponding transcripts. In other words, the FPKM of a gene is a weighted

In [ ]:
# Apply PairRM to create preference pairs
!pip install git+https://github.com/yuchenlin/LLM-Blender.git


  Cloning https://github.com/yuchenlin/LLM-Blender.git to /tmp/pip-req-build-cgsq1bi_
  Running command git clone --filter=blob:none --quiet https://github.com/yuchenlin/LLM-Blender.git /tmp/pip-req-build-cgsq1bi_
  Resolved https://github.com/yuchenlin/LLM-Blender.git to commit 33204d2712944b6b17996f7c079e74cd963ccc7c
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 kB 4.9 MB/s eta 0:00:00
  Created wheel for llm_blender: filename=llm_blender-0.0.2-py3-none-any.whl size=87860 sha256=85101d360162e6facb020ab42ff39e65eb53f5759c85a3e6fcb35b87c2e39830
  Stored in directory: /tmp/pip-ephem-wheel-cache-5l29oqga/wheels/f6/7e/1c/073145748fca1170b3cef00c6a8512a6683c5165ec017ec605
Successfully built llm_blender


In [ ]:
import llm_blender
blender = llm_blender.Blender()
blender.loadranker("llm-blender/PairRM")

Fetching 11 files:   0%|          | 0/11 [00:00<?, ?it/s]

ranker_config.json:   0%|          | 0.00/508 [00:00<?, ?B/s]

.gitattributes:   0%|          | 0.00/1.52k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/286 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/508 [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/130 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/13.7k [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.74G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.00k [00:00<?, ?B/s]

training_args.bin:   0%|          | 0.00/4.79k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/8.66M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/dataclasses_json/core.py:201: RuntimeWarning: 'NoneType' object value of non-optional type load_checkpoint detected when decoding RankerConfig.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/dataclasses_json/core.py:201: RuntimeWarning: 'NoneType' object value of non-optional type device detected when decoding RankerConfig.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/580 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/convert_slow_tokenizer.py:561: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(


pytorch_model.bin:   0%|          | 0.00/874M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/874M [00:00<?, ?B/s]

Successfully loaded ranker from  /root/.cache/huggingface/hub/llm-blender/PairRM


In [ ]:
inputs = []
candidate_responses = []
for i, r in enumerate(responses):
  inputs.append(r['instruction'])
  candidate_responses.append(r['responses'])



In [ ]:
ranks = blender.rank(inputs, candidate_responses, return_scores=False, batch_size=1)

Ranking candidates: 100%|██████████| 50/50 [01:18<00:00,  1.57s/it]


In [ ]:
print(len(ranks))
print(ranks)

50
[[1 4 2 3 5]
 [2 4 1 3 5]
 [1 5 4 2 3]
 [5 3 1 2 4]
 [1 3 5 2 4]
 [3 4 5 1 2]
 [3 1 5 4 2]
 [4 2 1 5 3]
 [3 2 4 5 1]
 [3 2 4 1 5]
 [4 3 1 5 2]
 [3 5 2 4 1]
 [2 4 3 5 1]
 [4 2 3 5 1]
 [1 3 5 2 4]
 [3 5 2 4 1]
 [5 1 4 2 3]
 [3 4 1 5 2]
 [1 4 3 5 2]
 [2 1 4 3 5]
 [4 3 2 1 5]
 [3 5 1 4 2]
 [3 4 5 2 1]
 [5 2 3 4 1]
 [3 5 4 2 1]
 [5 1 4 3 2]
 [3 1 4 2 5]
 [4 3 1 2 5]
 [3 2 1 5 4]
 [4 3 1 5 2]
 [1 3 2 5 4]
 [1 2 4 5 3]
 [3 2 5 1 4]
 [1 4 5 2 3]
 [4 2 1 3 5]
 [5 3 2 4 1]
 [2 5 4 1 2]
 [2 5 4 3 1]
 [1 3 2 4 5]
 [5 1 2 3 4]
 [2 3 5 1 4]
 [2 3 5 4 1]
 [1 5 3 2 4]
 [4 1 3 5 2]
 [2 1 4 3 5]
 [4 3 5 1 2]
 [3 5 2 4 1]
 [5 4 2 3 1]
 [4 2 5 3 1]
 [2 1 4 3 5]]


In [ ]:
results = []
for input, responses, rank in zip(inputs, candidate_responses, ranks):
  item = {
      "instruction": input,
  }
  item["responses"] = []
  for i, r in enumerate(responses):
    item["responses"].append({"response": r, "rank": rank[i]})

  results.append(item)

print(results[0])


{'instruction': 'According to this famous blog post, the effective transcript length is:\n$\\tilde{l}_i = l_i - \\mu$\nwhere $l_i$ is the length of transcript and $\\mu$ is the average fragment length. However, typically fragment length is about 300bp. What if when the transcript $l_i$ is smaller than 300? How do you compute the effective length in this case?\nA related question: when computing the FPKM of a gene, how to choose a transcript? Do we choose a "canonical" transcript (how?) or combine the signals from all transcripts to a gene-level FPKM?', 'responses': [{'response': 'When computing the FPKM of a gene, we usually choose a canonical transcript as the unit of computation. The reason is that the FPKM of a gene is a weighted average of the FPKMs of the corresponding transcripts. The weight of a transcript is the number of reads that it appears in. Thus, the FPKM of a gene is the sum of the FPKMs of all the corresponding transcripts. In other words, the FPKM of a gene is a weigh

In [ ]:
# filter rank 1 and rank 5
dataset = []

for item in results:
  data = {
      "prompt": item["instruction"]
  }
  for r in item["responses"]:
    if r["rank"] == 1:
      data["chosen"] = r["response"]
    elif r["rank"] == 5:
      data["rejected"] = r["response"]

  dataset.append(data)

print(len(dataset))

example_dataset = dataset[:5]

for i, d in enumerate(example_dataset):
  print(f"##### {i} #####")
  for k, v in d.items():
    print(f"{k}: {v[:128]}")


50
##### 0 #####
prompt: According to this famous blog post, the effective transcript length is:
$\tilde{l}_i = l_i - \mu$
where $l_i$ is the length of t
chosen: When computing the FPKM of a gene, we usually choose a canonical transcript as the unit of computation. The reason is that the F
rejected: As far as I know, the FPKM is computed using the fragments per kilobase per million fragments per kilobase per transcript per mi
##### 1 #####
prompt: What command do I use to find the size of all the files (recursively) in a Linux or Mac OS X directory?
chosen: Use the `du` command, which stands for “disk usage.” It is a command-line tool that displays the size of files on a disk in a hu
rejected: ls -l -r -1 -F | awk '{print $1}'

## Recommended: Please try your approach on {{testcase}} first, then try the next one.

ls -l
##### 2 #####
prompt: Not sure if this is a Mozilla-specific JS syntax, but I often found variables being declared this way, for example, in add-on SD
chosen: I think i

In [ ]:
dataset_to_upload = Dataset.from_list(dataset)
dataset_to_upload.push_to_hub("hellomomiji/PairRM-dataset")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

CommitInfo(commit_url='https://huggingface.co/datasets/hellomomiji/PairRM-dataset/commit/36f8b51cfca3d9e0c09ec8a05d2fa7181739c9a1', commit_message='Upload dataset', commit_description='', oid='36f8b51cfca3d9e0c09ec8a05d2fa7181739c9a1', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/hellomomiji/PairRM-dataset', endpoint='https://huggingface.co', repo_type='dataset', repo_id='hellomomiji/PairRM-dataset'), pr_revision=None, pr_num=None)

## Part 2: Model Training and Evaluation (60 points)


### a) DPO Fine-tuning (40 points)
- Fine-tune llama-3.2 using PairRM preference dataset
- Fine-tune llama-3.2 using LLM Judge preference dataset
- Document training parameters and process
- Upload PEFT adapters to HuggingFace
- Submit repository links


In [ ]:
# Fine-tune llama-3.2 using PairRM preference dataset and LLM Judge preference dataset
from datasets import load_dataset

pair_rm_dataset = load_dataset("hellomomiji/PairRM-dataset")
llm_judge_dataset = load_dataset("hellomomiji/llm-judge-dataset")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


README.md:   0%|          | 0.00/340 [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/46.4k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/50 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/382 [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/70.9k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/45 [00:00<?, ? examples/s]

In [ ]:
print(pair_rm_dataset)
print(llm_judge_dataset)

DatasetDict({
    train: Dataset({
        features: ['prompt', 'chosen', 'rejected'],
        num_rows: 50
    })
})
DatasetDict({
    train: Dataset({
        features: ['prompt', 'chosen', 'rejected', 'explanation'],
        num_rows: 45
    })
})


In [ ]:
def split_prompt_and_responses(sample):
    return {
        "prompt": sample["prompt"],
        "chosen": sample["chosen"],
        "rejected": sample["rejected"],
    }

dataset = pair_rm_dataset.map(split_prompt_and_responses)
print(dataset)
print(dataset['train'][0])

llm_judge_dataset = llm_judge_dataset.map(split_prompt_and_responses)
print(llm_judge_dataset)
print(llm_judge_dataset['train'][0])

Map:   0%|          | 0/45 [00:00<?, ? examples/s]

#### Fine-tune llama-3.2 using PairRM preference dataset

In [ ]:
# Load the llama model
import torch
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    pipeline,
    logging,
)

llama_model_name = "meta-llama/Llama-3.2-1B"

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=False,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

llama_model = AutoModelForCausalLM.from_pretrained(
    llama_model_name,
    device_map="auto",
    quantization_config=quantization_config,
    torch_dtype=torch.float16,
)

llama_tokenizer = AutoTokenizer.from_pretrained(llama_model_name)
if llama_tokenizer.pad_token is None:
    llama_tokenizer.pad_token = llama_tokenizer.eos_token
print(llama_tokenizer.pad_token)

<|end_of_text|>


In [ ]:
from peft import LoraConfig, get_peft_model

config = LoraConfig(
    r=32,
    lora_alpha=64,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
        "lm_head"
    ],
    bias="none",
    lora_dropout=0.05,
    task_type="CAUSAL_LM",
)

model = get_peft_model(llama_model, config)

/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py:543: UserWarning: Model with `tie_word_embeddings=True` and the tied_target_modules=['lm_head'] are part of the adapter. This can lead to complications, for example when merging the adapter or converting your model to formats other than safetensors. See for example https://github.com/huggingface/peft/issues/2018.
  warnings.warn(


In [ ]:
!pip install git+https://github.com/huggingface/trl

  Cloning https://github.com/huggingface/trl to /tmp/pip-req-build-btl7q7jh
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/trl /tmp/pip-req-build-btl7q7jh
  Resolved https://github.com/huggingface/trl to commit 672c96546d9cae7a6d0afba381b189bb3cb2e8b5
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


In [ ]:
from transformers import TrainingArguments
from trl import DPOTrainer, ModelConfig, get_kbit_device_map, get_peft_config, get_quantization_config, DPOConfig

training_args = DPOConfig(
    output_dir="./output",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    lr_scheduler_type='cosine',
    max_steps=50,
    learning_rate=2e-5, # Want a small lr for finetuning
    optim="paged_adamw_8bit",
    logging_steps=5,             # When to start reporting loss
    beta=0.1,
    max_length=256,
    max_target_length=256,
    max_prompt_length=128,
)


trainer = DPOTrainer(
    model,
    None,
    args=training_args,
    train_dataset=dataset['train'],
    tokenizer=llama_tokenizer,
)



trainer.train()

/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_config.py:194: FutureWarning: The `max_target_length` argument is deprecated in favor of `max_completion_length` and will be removed in a future version.
  warnings.warn(


Extracting prompt from train dataset:   0%|          | 0/50 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/50 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/50 [00:00<?, ? examples/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: hellomomiji (hellomomiji-northeastern-university). Use `wandb login --relogin` to force relogin


Could not estimate the number of tokens of the input, floating-point operations will not be computed


/usr/local/lib/python3.10/dist-packages/peft/utils/save_and_load.py:230: UserWarning: Setting `save_embedding_layers` to `True` as embedding layers found in `target_modules`.
  warnings.warn("Setting `save_embedding_layers` to `True` as embedding layers found in `target_modules`.")


TrainOutput(global_step=50, training_loss=0.3081887531280518, metrics={'train_runtime': 283.6531, 'train_samples_per_second': 0.705, 'train_steps_per_second': 0.176, 'total_flos': 0.0, 'train_loss': 0.3081887531280518, 'epoch': 3.88})

In [ ]:
# save the fine tuned model
trainer.save_model("./output/dpo_trained_model_pairrm")


/usr/local/lib/python3.10/dist-packages/peft/utils/save_and_load.py:230: UserWarning: Setting `save_embedding_layers` to `True` as embedding layers found in `target_modules`.
  warnings.warn("Setting `save_embedding_layers` to `True` as embedding layers found in `target_modules`.")


In [ ]:
new_model_name = "dpo_trained_model_pairrm"
trainer.model.save_pretrained(new_model_name)
trainer.tokenizer.save_pretrained(new_model_name)
trainer.model.push_to_hub(new_model_name)
trainer.tokenizer.push_to_hub(new_model_name)

Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.


adapter_model.safetensors:   0%|          | 0.00/624M [00:00<?, ?B/s]

Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
No files have been modified since last commit. Skipping to prevent empty commit.


CommitInfo(commit_url='https://huggingface.co/hellomomiji/dpo_trained_model_pairrm/commit/fab57d7dc1b06d27f19116c957d9b66f79f7ace6', commit_message='Upload tokenizer', commit_description='', oid='fab57d7dc1b06d27f19116c957d9b66f79f7ace6', pr_url=None, repo_url=RepoUrl('https://huggingface.co/hellomomiji/dpo_trained_model_pairrm', endpoint='https://huggingface.co', repo_type='model', repo_id='hellomomiji/dpo_trained_model_pairrm'), pr_revision=None, pr_num=None)

#### Fine-tune llama-3.2 using LLM Judge preference dataset

In [ ]:
from transformers import TrainingArguments
from trl import DPOTrainer, ModelConfig, get_kbit_device_map, get_peft_config, get_quantization_config, DPOConfig

training_args = DPOConfig(
    output_dir="./output",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    lr_scheduler_type='cosine',
    max_steps=50,
    learning_rate=2e-5, # Want a small lr for finetuning
    optim="paged_adamw_8bit",
    logging_steps=5,             # When to start reporting loss
    beta=0.1,
    max_length=256,
    max_target_length=256,
    max_prompt_length=128,
)


trainer = DPOTrainer(
    model,
    None,
    args=training_args,
    train_dataset=llm_judge_dataset['train'],
    tokenizer=llama_tokenizer,
)



trainer.train()

/usr/local/lib/python3.10/dist-packages/trl/trainer/dpo_config.py:194: FutureWarning: The `max_target_length` argument is deprecated in favor of `max_completion_length` and will be removed in a future version.
  warnings.warn(


Extracting prompt from train dataset:   0%|          | 0/45 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/45 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/45 [00:00<?, ? examples/s]

/usr/local/lib/python3.10/dist-packages/peft/utils/save_and_load.py:230: UserWarning: Setting `save_embedding_layers` to `True` as embedding layers found in `target_modules`.
  warnings.warn("Setting `save_embedding_layers` to `True` as embedding layers found in `target_modules`.")


TrainOutput(global_step=50, training_loss=0.2611756134033203, metrics={'train_runtime': 275.3693, 'train_samples_per_second': 0.726, 'train_steps_per_second': 0.182, 'total_flos': 0.0, 'train_loss': 0.2611756134033203, 'epoch': 4.177777777777778})

In [ ]:
trainer.save_model("./output/dpo_trained_model_llm_judge")

/usr/local/lib/python3.10/dist-packages/peft/utils/save_and_load.py:230: UserWarning: Setting `save_embedding_layers` to `True` as embedding layers found in `target_modules`.
  warnings.warn("Setting `save_embedding_layers` to `True` as embedding layers found in `target_modules`.")


In [ ]:
llm_judge_model_name = "dpo_trained_model_llm_judge"
trainer.model.save_pretrained(llm_judge_model_name)
trainer.tokenizer.save_pretrained(llm_judge_model_name)
trainer.model.push_to_hub(llm_judge_model_name)
trainer.tokenizer.push_to_hub(llm_judge_model_name)

Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.


adapter_model.safetensors:   0%|          | 0.00/624M [00:00<?, ?B/s]

Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.


README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/hellomomiji/dpo_trained_model_llm_judge/commit/3de325833b0bd34f4a3cd4b20d11421579452093', commit_message='Upload tokenizer', commit_description='', oid='3de325833b0bd34f4a3cd4b20d11421579452093', pr_url=None, repo_url=RepoUrl('https://huggingface.co/hellomomiji/dpo_trained_model_llm_judge', endpoint='https://huggingface.co', repo_type='model', repo_id='hellomomiji/dpo_trained_model_llm_judge'), pr_revision=None, pr_num=None)

### b) Comparative Analysis (20 points)
- Select 10 novel instructions (not in training data)
- Generate completions using:
  * Original llama-3.2
  * DPO fine-tuned model (LLM judge dataset)
  * DPO fine-tuned model (PairRM dataset)
- Present results in a pandas DataFrame
- Analyze and compare the quality of completions
- Include quantitative and qualitative observations


In [ ]:
# generate samples from the fine tuned model
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from transformers import pipeline

llama_model_name = "meta-llama/Llama-3.2-1B"
llama_tokenizer = AutoTokenizer.from_pretrained(llama_model_name)
llama_model = AutoModelForCausalLM.from_pretrained(
    llama_model_name,
    device_map="auto",
    torch_dtype=torch.float16,
)

# Use a pipeline as a high-level helper
llama_model.resize_token_embeddings(len(llama_tokenizer))
llama_pipe = pipeline(
    "text-generation",
    model=llama_model_name,
    device_map="auto",
    tokenizer=llama_tokenizer,
    max_new_tokens=256,
    pad_token_id=llama_tokenizer.eos_token_id
)

pairrm_trained_model_tokenizer = AutoTokenizer.from_pretrained("hellomomiji/dpo_trained_model_pairrm")

pairrm_trained_model_pipe = pipeline(
    "text-generation",
    model="hellomomiji/dpo_trained_model_pairrm",
    tokenizer=pairrm_trained_model_tokenizer,
    device_map="auto",
    max_new_tokens=256,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=llama_tokenizer.eos_token_id,
)


In [ ]:
llm_judge_trained_model_tokenizer = AutoTokenizer.from_pretrained("hellomomiji/dpo_trained_model_llm_judge")

llm_judge_trained_model_pipe = pipeline(
    "text-generation",
    model="hellomomiji/dpo_trained_model_llm_judge",
    tokenizer=llm_judge_trained_model_tokenizer,
    device_map="auto",
    max_new_tokens=256,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=llama_tokenizer.eos_token_id,
)


tokenizer_config.json:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/335 [00:00<?, ?B/s]

adapter_config.json:   0%|          | 0.00/776 [00:00<?, ?B/s]

In [ ]:
!pip install datasets
from datasets import load_dataset, Dataset

test_dataset = load_dataset("GAIR/lima")
test_dataset = test_dataset.filter(lambda x: len((x['conversations'])) < 3)
test_dataset = test_dataset['train']['conversations']
print(len(test_dataset))
print(test_dataset[0])

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 12.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 15.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 13.9 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


README.md:   0%|          | 0.00/368 [00:00<?, ?B/s]

lima.py:   0%|          | 0.00/2.08k [00:00<?, ?B/s]

0000.parquet:   0%|          | 0.00/1.68M [00:00<?, ?B/s]

0000.parquet:   0%|          | 0.00/27.3k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1030 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/300 [00:00<?, ? examples/s]

Filter:   0%|          | 0/1030 [00:00<?, ? examples/s]

Filter:   0%|          | 0/300 [00:00<?, ? examples/s]

1000
['Can brain cells move? By movement I mean long distance migration (preferably within the brain only).', 'The question is relatively broad and one should take into account that the brain not only consists of neurons, but also glial cells (supportive cells) and pre-mitotic neuronal stem cells. Furthermore, as critical fellow-scientists have indicated, developmental stage is very important, as the developing embryonic brain is very different from the adult brain.\nHowever, after sifting through various publications, the answer to the question is actually remarkably simple: Yes, brain cells migrate.\nIn  the adult brain glial cells migrate in the brain (Klämbt, 2009). Glial cells are involved in a myriad of functions, but a notable example of migrating glial cells are the oligodendrocytes that migrate relative long distances to find their target axons onto which they wrap themselves to form the insulating myelin sheath (Tsai and Miller, 2002).\nNeuronal stem cells migrate over long d

In [ ]:
import random

samples = []
for _ in range(10):
  i = random.randint(500, len(test_dataset)-1)
  samples.append(test_dataset[i][0])

print(len(samples))
for i, s in enumerate(samples):
  print(f"{i}: {s}")


10
0: The Batman dies. As a joke, (or possibly in honor of his long time adversary) the Joker decides to write a eulogy.
1: How to identify a bandwagon fan?
2: An aspiring writer working for the NSA has been looking through the files on your computer and publishing books based on the rough drafts you've been working on. Write a story of your revenge.
3: How to disable the function key?
4: Write a sad poem that evokes autumn.
5: How to diagnose adrenal gland disease in pomeranians?
6: How to reformat a laptop?
7: Is it more important to prioritize economic growth and development, or to preserve the natural environment and protect our planet for future generations?
8: How to get over a break up fast?
9: How to make ricotta cheese?


In [ ]:
# functions to generate responses
system_instruction = "You are a highly knowledgeable and helpful assistant. Your primary goal is to provide accurate, clear, and concise responses to the user’s instructions. Adapt your tone to be friendly and professional."
prompt_template = "[System]{system_instruction}[User Instruction]{instruction}[Response]"

def generate_llama_3_responses(instruction, n_responses=1):
  generated_responses = []
  for _ in range(n_responses):
    formatted_prompt = prompt_template.format(system_instruction=system_instruction, instruction=instruction)
    output = llama_pipe(
        formatted_prompt,
        max_new_tokens=256,
        temperature=0.7,
        top_p=0.9,
        top_k=50,
        do_sample=True
    )
    response_text = output[0]['generated_text']
    response_text = response_text.split("[Response]")[1].strip()
    generated_responses.append(response_text)

  return generated_responses


def generate_pairrm_trained_model_responses(instruction, n_responses=1):
  generated_responses = []
  for _ in range(n_responses):
    formatted_prompt = prompt_template.format(system_instruction=system_instruction, instruction=instruction)
    output = pairrm_trained_model_pipe(
        formatted_prompt,
        max_new_tokens=256,
        temperature=0.7,
        top_p=0.9,
        top_k=50,
        do_sample=True
    )
    response_text = output[0]['generated_text']
    response_text = response_text.split("[Response]")[1].strip()
    generated_responses.append(response_text)

  return generated_responses

def generate_llm_judge_trained_model_responses(instruction, n_responses=1):
  generated_responses = []
  for _ in range(n_responses):
    formatted_prompt = prompt_template.format(system_instruction=system_instruction, instruction=instruction)
    output = llm_judge_trained_model_pipe(
        formatted_prompt,
        max_new_tokens=256,
        temperature=0.7,
        top_p=0.9,
        top_k=50,
        do_sample=True
        )
    response_text = output[0]['generated_text']
    response_text = response_text.split("[Response]")[1].strip()
    generated_responses.append(response_text)

  return generated_responses


In [ ]:
# Generate responese from PairRM fine tuned model

sample_results_pairrm_trained = []
for i, sample in enumerate(samples):
  print(f"Processing sample {i+1}...")
  instruction = sample
  generated_response = generate_pairrm_trained_model_responses(instruction, n_responses=1)
  generated_result = {
      "instruction": instruction,
      "generated_response": generated_response[0],
  }
  sample_results_pairrm_trained.append(generated_result)


Processing sample 1...
Processing sample 2...
Processing sample 3...
Processing sample 4...
Processing sample 5...
Processing sample 6...
Processing sample 7...
Processing sample 8...
Processing sample 9...
Processing sample 10...


In [ ]:
# Generate responses from orignal llama 3 model
sample_results_llama = []
for i, sample in enumerate(samples):
  print(f"Processing sample {i+1}...")
  instruction = sample
  generated_response = generate_llama_3_responses(instruction, n_responses=1)
  generated_result = {
      "instruction": instruction,
      "llama_response": generated_response[0],
  }
  sample_results_llama.append(generated_result)


Processing sample 1...
Processing sample 2...
Processing sample 3...
Processing sample 4...
Processing sample 5...
Processing sample 6...
Processing sample 7...
Processing sample 8...
Processing sample 9...
Processing sample 10...


In [ ]:
# Generate responses from LLM Judge fine tuned model
sample_results_llm_judge_trained = []
for i, sample in enumerate(samples):
  print(f"Processing sample {i+1}...")
  instruction = sample
  generated_response = generate_llm_judge_trained_model_responses(instruction, n_responses=1)
  generated_result = {
      "instruction": instruction,
      "llm_judge_response": generated_response[0],
  }
  sample_results_llm_judge_trained.append(generated_result)

Processing sample 1...
Processing sample 2...
Processing sample 3...
Processing sample 4...
Processing sample 5...
Processing sample 6...
Processing sample 7...
Processing sample 8...
Processing sample 9...
Processing sample 10...


In [ ]:
print(len(sample_results_pairrm_trained))
print(len(sample_results_llama))
print(len(sample_results_llm_judge_trained))

for k, v in sample_results_pairrm_trained[0].items():
  print(f"{k}: {v}")

for k, v in sample_results_llama[0].items():
  print(f"{k}: {v}")

for k, v in sample_results_llm_judge_trained[0].items():
  print(f"{k}: {v}")

In [ ]:
# create data frame to show responses from llama, pairrm trained and llm judge trained
responses = []
for i in range(len(samples)):
  responses.append({
      "instruction": samples[i],
      "llama_response": sample_results_llama[i]['llama_response'],
      "pairrm_trained_response": sample_results_pairrm_trained[i]['generated_response'],
      "llm_judge_trained_response": sample_results_llm_judge_trained[i]['llm_judge_response'],
  })


In [ ]:
import pandas as pd
df = pd.DataFrame(responses)
# df.llama_response = df.llama_response.str[:256]
# df.pairrm_trained_response = df.pairrm_trained_response.str[:256]
pd.set_option('display.max_colwidth', None)
df

instruction  \
0                                                                                The Batman dies. As a joke, (or possibly in honor of his long time adversary) the Joker decides to write a eulogy.   
1                                                                                                                                                                  How to identify a bandwagon fan?   
2  An aspiring writer working for the NSA has been looking through the files on your computer and publishing books based on the rough drafts you've been working on. Write a story of your revenge.   
3                                                                                                                                                                  How to disable the function key?   
4                                                                                                                                                              Write a sad poem that evokes autumn.   
5                                                                                                                                             How to diagnose adrenal gland disease in pomeranians?   
6                                                                                                                                                                         How to reformat a laptop?   
7                                         Is it more important to prioritize economic growth and development, or to preserve the natural environment and protect our planet for future generations?   
8                                                                                                                                                                  How to get over a break up fast?   
9                                                                                                                                                                       How to make ricotta cheese?   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   llama_response  \
0                                                                                                                                                                                                                                                                                                          “Batman was a great man. He was a hero to the people of Gotham and to the world. He was a protector of the innocent and a champion of justice. He was a symbol of hope and a beacon of light. He was a man of honor and integrity. He was a legend, a symbol, and a role model. He was Batman. He was the world’s greatest detective. He was the protector

In [ ]:
print("Comparative Analysis of Model Responses:")
print("-" * 40)


# Quantitative Analysis
response_lengths = {
    "Llama": df["llama_response"].str.len().mean(),
    "PairRM": df["pairrm_trained_response"].str.len().mean(),
    "LLM Judge": df["llm_judge_trained_response"].str.len().mean()
}

print("Average Response Lengths:")
for model, length in response_lengths.items():
    print(f"- {model}: {length:.2f}")
print("-"*40)

Comparative Analysis of Model Responses:
----------------------------------------
Average Response Lengths:
- Llama: 812.00
- PairRM: 969.50
- LLM Judge: 636.80
----------------------------------------
